name: pin_note
description: "A Flutter notepad application similar to ColorNote with Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # SQLite for local storage
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # State Management
  flutter_bloc: ^9.1.0
  
  # Functional programming & immutable data
  freezed_annotation: ^3.0.0
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Routing
  go_router: ^15.1.2
  
  # Utilities
  equatable: ^2.0.7
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0

flutter:
  uses-material-design: true
